"""empty message

Revision ID: 072203572b3f
Revises: c1b9cd9c0f11
Create Date: 2017-11-26 16:07:39.121608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072203572b3f'
down_revision = 'c1b9cd9c0f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###
